api/urls.py
from django.urls import path 
from .views import BlogAPIView ,MusicAPIView ,AlbumAPIView

app_name ='api'

urlpatterns = [
path('',BlogAPIView.as_view(), name='blog_api' ),
path('music/',MusicAPIView.as_view(), name='music_api' ),
path('album/',AlbumAPIView.as_view(), name='album_api' ),
]

blog/urls.py
from django.urls import path 
from .views import home ,detail
app_name= 'blog'
urlpatterns = [
  path('',home, name= 'home'),
  path('<slug:slug>/<int:pk>/',detail, name= 'detail'),
]

music/urls.py
from django.urls import path 
from .views import home ,detail

app_name ='music'

urlpatterns = [
  path('',home ,name ='home'),
  path('<slug:slug>/<int:pk>', detail , name = 'detail')
]

zareb/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('',include('music.urls')),
    path('api/',include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone 

class Category(models.Model):
  #parent  = models.ForeignKey(Category)
  body = models.CharField(max_length= 30)
  slug = models.SlugField(unique=True)
  status = models.BooleanField()
  position = models.IntegerField()
  created = models.DateTimeField(auto_now_add =True)    
  def __str__(self):
    return self.body
  class Meta:
    verbose_name= 'دستهبندی'
    verbose_name_plural = 'دسته بندی ها'
    ordering =('position',)



class Blog(models.Model):
  STATUS_CHOICIES=(('p', 'انتشار'),('d', 'پیش نویس'))
  title =models.CharField(max_length=200 ,verbose_name='عنوان')
  cover = models.ImageField(upload_to ='blog-cover', verbose_name='عکس بندانگشتی')
  desc  = models.TextField(verbose_name = 'توضیحات', blank =True , null =True)
  slug =models.SlugField(unique=True,verbose_name='ادرس')
  publish_time = models.DateTimeField(default=timezone.now,verbose_name='زمان انتشار')
  created =models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)
  status = models.CharField(max_length=1, choices= STATUS_CHOICIES)
  pin = models.BooleanField(default=False)
  category = models.ManyToManyField(Category)
  def __str__(self):
    return self.title
  class Meta:
    verbose_name='وبلاگ'
    verbose_name_plural = 'وبلاگ ها'
    ordering = ['publish_time']

music/models.py
from django.db import models
from django.utils import timezone 
# Create your models here.

class Album(models.Model):
  name = models.CharField(max_length=200 ,verbose_name='نام البوم')
  rapper =models.CharField(max_length=200 ,verbose_name='نام خواننده')
  slug = models.SlugField(unique=True,verbose_name='ادرس')
  cover = models.ImageField(upload_to ='music-cover', verbose_name='کاور')
  publish_time = models.DateTimeField(default=timezone.now,verbose_name='زمان انتشار')
  created =models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)
  label =models.CharField(max_length=50 ,verbose_name=' لیبل', blank =True , null =True)
  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name='البوم'
    verbose_name_plural = 'البوم ها'
    ordering = ['publish_time']



class Music(models.Model):
  name = models.CharField(max_length=200 ,verbose_name='نام اهنگ')
  rapper =models.CharField(max_length=200 ,verbose_name='نام خواننده')
  album = models.ForeignKey(Album,blank =True , null =True,on_delete = models.CASCADE)
  label =models.CharField(max_length=50 ,verbose_name=' لیبل', blank =True , null =True)
  mix_mastering = models.CharField(max_length=200,blank =True , null =True)
  cover = models.ImageField(upload_to ='music-cover', verbose_name='کاور')
  cover_art = models.CharField(max_length=100 , blank =True , null =True)
  file = models.FileField(upload_to='music_file',verbose_name='فایل صوتی ')
  slug =models.SlugField(unique=True,verbose_name='ادرس')
  publish_time = models.DateTimeField(default=timezone.now,verbose_name='زمان انتشار')
  created =models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)
  show =models.BooleanField(default = True,verbose_name='نمایش/عدم نمایش')
  des  = models.TextField(verbose_name = 'توضیحات', blank =True , null =True)

  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name='موسیقی'
    verbose_name_plural = 'موسیقی ها'
    ordering = ['publish_time']

api/views.py
from django.shortcuts import render

from blog.models import Blog ,Category 
from music.models import Music , Album
from rest_framework  import generics
from .serializers import BlogSerializer ,MusicSerializer ,AlbumSerializer

class BlogAPIView(generics.ListAPIView):
  queryset = Blog.objects.filter(status= 'p')
  serializer_class  = BlogSerializer


class MusicAPIView(generics.ListAPIView):
  queryset = Music.objects.filter(show= True)
  serializer_class  = MusicSerializer


class AlbumAPIView(generics.ListAPIView):
  queryset = Album.objects.all()
  serializer_class = AlbumSerializer

blog/views.py
from django.shortcuts import render
from .models import Blog


def home(request):
  blogs = Blog.objects.filter(status='p')
  return render(request,'blog/index.html',{
    'blogs':blogs
  })


def detail(request ,pk , slug):
  blogs = Blog.objects.filter(status='p' ,pk= pk )
  return render(request,'blog/detail.html',{
    'blogs':blogs
  })

music/views.py
from django.shortcuts import render ,get_object_or_404
from .models import Music , Album
from django.core.paginator import Paginator
# Create your views here.

def home(request):
  musics = Music.objects.filter(show=True)
 
  context ={
    'musics':musics
  }
  return render(request,'music/home.html',context)


def detail(request ,pk,slug):
  musics =get_object_or_404(Music , pk=pk , show= True) 
 
  context ={
    'music':musics
  }
  return render(request,'music/detail.html',context)

blog/templates/blog/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'music/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/blog-post.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">
      {% for blog in blogs%}
      <div class="col-lg-8">
      
        <!-- Title -->
        <h1 class="mt-4">{{blog.title}}</h1>
        <hr>
      
        <!-- Date/Time -->
        <p>Posted on {{blog.publish_time}}</p>
      
        <hr>
      
        <!-- Preview Image -->
        <!-- <img class="img-fluid rounded" src="http://placehold.it/900x300" alt=""> -->
      
        <hr>
      
        <!-- Post Content -->
        <p class="lead">{{blog.desc|truncatewords:30|linebreaks}}
        </p>
        <blockquote class="blockquote">
          <p class="mb-0">{% for cat in blog.category.all%}<span class =' badge badge-dark'>{{cat.body}}</span>{%endfor%}</p>
        </blockquote>
      
      
      
        <hr>
      </div>
      {% endfor%}      
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'music/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'music/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

music/templates/music/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block title%}{%endblock%}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="{% static 'music/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark ">
    <div class="collapse navbar-collapse">
      <a href="#" class='navbar-brand'>site </a>
      <button type="button" class="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav nav ">
        <li class="nav-item">
          <a href="{% url 'music:home'%}" class="nav-link active"><span class="sr-only">(current)</span>Home</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'music:home'%}" class="nav-link active"><span class="sr-only">(current)</span>Blog</a>
        </li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> About <span class="caret"></span></a>
          <div class="dropdown-menu">
            <div class="dropdown-header">
              شبکهای اجتماعی
            </div>
            <a href="#" class="dropdown-item">Telegram <span class="badge badge-primary badge-pill">2</span></a>
            <a href="#" class="dropdown-item">tweater</a>
            <a href="#" class="dropdown-item">Instagram</a>
            <div class="dropdown-divider">

            </div>
            <a href="#" class="dropdown-item">Email</a>

          </div>

        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Contact</a></li>
      </ul>
    </div>
  </nav>
    {% block content %}{% endblock%}
  </body>
</footer>

<script src="{% static 'music/vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'music/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

</html>

music/templates/music/detail.html
{% extends './base.html'%}


{% block title%}{{music.name}}{%endblock%}

{%block content%}
<div class='container'>
  <div class="col col-sm-12 col-md-12 col-lg-12 mt-3">
    <img src="{{music.cover.url}}" class='rounded  mt-3' height="500px" width="500px">
    <audio controls>
      <source src="{{music.file.url}}" type="audio/ogg">
      <source src="{{music.file.url}}" type="audio/mpeg">
    </audio> 
  </div>
  <div>
    <ul>
       <li> {{music.name}}</li>
       <li> {{music.rapper}}</li>
       <li> {{music.label}}</li>
       <li> {{music.mix_mastering}}</li>
       <li> {{music.cover_art}}</li>
       <li> {{music.des}}</li>
    </ul>
  
  </div>
  </div>
{% endblock content%}

music/templates/music/home.html
{% extends './base.html'%}
{% block title%} Music{%endblock%}
{% block content %}
<div class="container pt-4">
  <h1>Music</h1> 
  <div class ='row'>
{% for music in musics %}
    <div class="col col-md-3  col-lg-3 col-sm-4 col-xs-4 mx-auto my-auto">
      <a href="{% url 'music:detail' music.slug music.pk%}"><img src="{{music.cover.url}}" class='img-fluid rounded' height="300" width="300" alt=""></a>
      <h4>{{music.name}}</h4>  
    </div>
{% endfor %}
</div>
  </div>
{% endblock%}